services:
  db:
    container_name: gomoviesdb-db
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
